version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: pdfmaster
      POSTGRES_PASSWORD: pdfmaster
      POSTGRES_DB: pdfmaster
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://pdfmaster:pdfmaster@db:5432/pdfmaster
      - JWT_SECRET=your_jwt_secret_key_here
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
