[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16.14.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "vite"
  targetPort = 3000
  command = "npm run dev"
